---
# The name of the plugin; official plugins always start "jellyfin-plugin-"
name: "Jellyscrubberr"

# The GUID of the plugin, found in Plugin.cs
guid: "6b961c92-5678-45d1-a7ac-dd5003f03460"

# The version of the plugin, starting at 1. Note that the AssemblyVersion
# and FileVersion flags in the `.csproj` file must have two additional
# fiels, e.g. 1.0.0 to be built correctly.
version: "1" # Please increment with each pull request

# The supported Jellyfin version, usually the earliest binary-compatible
# version. Based on the Jellyfin components from NuGet.
targetAbi: "10.3.0" # The earliest binary-compatible version

# The owner name of the plugin, "jellyfin" for official plugins. Change
# to your own name if you wish to remain a 3rd-party plugin.
owner: "CasperDoesCoding"

# A short description of the plugin
overview: "Alternative plugin for smooth video scrobbling in Jellyfin."

# A longer and more detailed description of the plugin; use multiple
# lines as required for readability.
description: >
This plugin generates trickplay files for videos in your library.
Trickplay files are used to generate thumbnails and allow for smooth seeking in videos.

# The plugin category, in a general sense. These fields are dynamic.
category: "General"

# A list of built artifacts to be bundled into the ZIP for installation.
# Include the main output file, as well as any dependency `.dll`s that
# might be required for the plugin to run.
artifacts:
  - "Casper.Plugin.Jellyscrubberr/bin/publish/Casper.Plugin.Jellyscrubberr.dll"

# Build information values for the build infrastructure; these should
# not need to be changed usually.
build_type: "dotnet"
dotnet_configuration: "Release"
dotnet_framework: "netstandard2.0"
