name: "Jellyscrubberr"

guid: "6b961c92-5678-45d1-a7ac-dd5003f03460"

version: "1"

targetAbi: "10.3.0"

owner: "CasperDoesCoding"

overview: "Alternative plugin for smooth video scrobbling in Jellyfin."

description: "This plugin generates trickplay files for videos in your library. Trickplay files are used to generate thumbnails and allow for smooth seeking in videos."

category: "General"

artifacts:
  - "Casper.Plugin.Jellyscrubberr/bin/publish/Casper.Plugin.Jellyscrubberr.dll"
  - "Casper.Plugin.Jellyscrubberr/bin/publish/MediaBrowser.Controller.dll"
  - "Casper.Plugin.Jellyscrubberr/bin/publish/MediaBrowser.Model.dll"

build_type: "dotnet"
dotnet_configuration: "Release"
dotnet_framework: "netstandard6.0"
