name: Jellyfin Plugin Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup .Net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "6.0.x"

      - name: Checkout Jellyfin Template Plugin
        uses: actions/checkout@v4
        with:
          repository: "jellyfin/jellyfin-plugin-template"
          path: "plugin-template"

      - name: Build Template Plugin with Action
        uses: ./
        id: jprm
        with:
          verbosity: "debug"
          path: "plugin-template"
          output: "plugin-template/artifacts"

      - name: List Output Artifact
        run: "ls -la ${{ steps.jprm.outputs.artifact }}"
