name: Jellyfin Plugin Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: jprm-build
        uses: oddstr13/jellyfin-plugin-repository-manager

      - name: Build Template Plugin with Action
        uses: ./
        id: jprm
        with:
          verbosity: "debug"
          output: "/artifacts"

      - name: List Output Artifact
        run: "ls -la ${{ steps.jprm.outputs.artifact }}"
